#!/bin/sh
set -eux
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

git filter-branch -f --msg-filter 'sed -Ee "s~ (#[0-9]+)~ Linuxbrew/linuxbrew\1~g"' -- 7814c5b9393a7dabc6b78e51bc21a7d3a6999dd2...master

git filter-branch -f --prune-empty \
  --index-filter 'git rm --cached --ignore-unmatch -r -q -- . ; git reset -q $GIT_COMMIT -- Library/Formula Library/Aliases;' \
  --msg-filter 'sed -Ee "s~ (#[0-9]+)~ Homebrew/homebrew\1~g"' \
  --env-filter ". $PWD/../env-filter.sh" \
  -- --all

git filter-branch -f --prune-empty --subdirectory-filter 'Library' -- --all
